[book]
title = "Plotly.rs Book"
author = "Ioannis Giagkiozis"
description = "Plotly.rs documentation"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "../../gh-pages/content"
create-missing = false
extra-watch-dirs = ["../../examples"]

[output.html]
default-theme = "Ayu"
mathjax-support = true
additional-css = ["ferris.css"]
additional-js = ["ferris.js", "plotly.min.js"]

[output.html.fold]
enable = true
level = 1
