//! Scatter-plot matrix (SPLOM) trace

use plotly_derive::FieldSetter;
use serde::Serialize;

use crate::{
    common::{Dim, HoverInfo, LegendGroupTitle, Marker, PlotType, Visible},
    layout::AxisType,
    Trace,
};

/// Per-dimension axis settings for a [`Splom`] dimension.
#[serde_with::skip_serializing_none]
#[derive(Serialize, Debug, Clone, FieldSetter)]
pub struct SplomAxis {
    /// Sets the axis type for this dimension's row/column.
    #[serde(rename = "type")]
    r#type: Option<AxisType>,
    /// Determines whether or not the x & y axes generated by this dimension
    /// match their corresponding axes on the other dimensions.
    matches: Option<bool>,
}

impl SplomAxis {
    pub fn new() -> Self {
        Default::default()
    }
}

/// A single dimension (column) of a [`Splom`] trace.
#[serde_with::skip_serializing_none]
#[derive(Serialize, Debug, Clone, FieldSetter)]
pub struct SplomDimension<V>
where
    V: Serialize + Clone,
{
    /// Sets the label corresponding to this splom dimension.
    label: Option<String>,
    /// Sets the dimension values to be plotted.
    values: Option<Vec<V>>,
    /// Determines whether or not this dimension is shown on the graph. Note that
    /// even visible false dimensions contribute to the default grid generation.
    visible: Option<bool>,
    /// Per-dimension axis settings.
    axis: Option<SplomAxis>,
}

impl<V> SplomDimension<V>
where
    V: Serialize + Clone,
{
    pub fn new() -> Self {
        Default::default()
    }
}

/// Controls the rendering of the SPLOM diagonal (where a dimension is plotted
/// against itself).
#[serde_with::skip_serializing_none]
#[derive(Serialize, Debug, Clone, FieldSetter)]
pub struct SplomDiagonal {
    /// Determines whether or not subplots on the diagonal are displayed.
    visible: Option<bool>,
}

impl SplomDiagonal {
    pub fn new() -> Self {
        Default::default()
    }
}

/// Construct a scatter-plot matrix (SPLOM) trace.
///
/// A `Splom` renders an N×N grid of scatter subplots, plotting every pair of
/// the supplied [`SplomDimension`]s against each other. Plotly.js generates the
/// axis grid automatically, so — unlike cartesian traces — you do not assign
/// explicit `xaxis`/`yaxis` ids.
///
/// # Examples
///
/// ```
/// use plotly::Splom;
/// use plotly::splom::SplomDimension;
///
/// let trace = Splom::new().dimensions(vec![
///     SplomDimension::new().label("A").values(vec![1, 2, 3]),
///     SplomDimension::new().label("B").values(vec![4, 5, 6]),
/// ]);
///
/// let expected = serde_json::json!({
///     "type": "splom",
///     "dimensions": [
///         {"label": "A", "values": [1, 2, 3]},
///         {"label": "B", "values": [4, 5, 6]}
///     ]
/// });
///
/// assert_eq!(serde_json::to_value(trace).unwrap(), expected);
/// ```
#[serde_with::skip_serializing_none]
#[derive(Serialize, Debug, Clone, FieldSetter)]
#[field_setter(box_self, kind = "trace")]
pub struct Splom<V>
where
    V: Serialize + Clone,
{
    #[field_setter(default = "PlotType::Splom")]
    r#type: PlotType,
    /// Sets the trace name. The trace name appears as the legend item and on
    /// hover.
    name: Option<String>,
    /// Determines whether or not this trace is visible. If "legendonly", the
    /// trace is not drawn, but can appear as a legend item.
    visible: Option<Visible>,
    /// Determines whether or not an item corresponding to this trace is shown in
    /// the legend.
    #[serde(rename = "showlegend")]
    show_legend: Option<bool>,
    /// Sets the legend group for this trace. Traces part of the same legend
    /// group show/hide at the same time when toggling legend items.
    #[serde(rename = "legendgroup")]
    legend_group: Option<String>,
    /// Set and style the title to appear for the legend group.
    #[serde(rename = "legendgrouptitle")]
    legend_group_title: Option<LegendGroupTitle>,
    /// Sets the opacity of the trace.
    opacity: Option<f64>,
    /// The dimensions (columns) plotted against each other in the matrix.
    dimensions: Option<Vec<SplomDimension<V>>>,
    /// Controls the rendering of the subplots on the diagonal.
    diagonal: Option<SplomDiagonal>,
    /// Determines whether or not subplots on the upper half of the matrix are
    /// displayed.
    #[serde(rename = "showupperhalf")]
    show_upper_half: Option<bool>,
    /// Determines whether or not subplots on the lower half of the matrix are
    /// displayed.
    #[serde(rename = "showlowerhalf")]
    show_lower_half: Option<bool>,
    /// Sets the marker style for the scatter points.
    marker: Option<Marker>,
    /// Sets the list of x axes corresponding to dimensions of this splom trace.
    /// Usually left unset so Plotly.js auto-lays-out the grid.
    xaxes: Option<Vec<String>>,
    /// Sets the list of y axes corresponding to dimensions of this splom trace.
    /// Usually left unset so Plotly.js auto-lays-out the grid.
    yaxes: Option<Vec<String>>,
    /// Sets text elements associated with each (x,y) pair to appear on hover.
    text: Option<Dim<String>>,
    /// Determines which trace information appears on hover.
    #[serde(rename = "hoverinfo")]
    hover_info: Option<HoverInfo>,
    /// Template string used for rendering the information that appear on hover
    /// box.
    #[serde(rename = "hovertemplate")]
    hover_template: Option<Dim<String>>,
}

impl<V> Splom<V>
where
    V: Serialize + Clone,
{
    /// Creates a new empty SPLOM trace.
    pub fn new() -> Box<Self> {
        Box::default()
    }
}

impl<V> Trace for Splom<V>
where
    V: Serialize + Clone,
{
    fn to_json(&self) -> String {
        serde_json::to_string(self).unwrap()
    }
}

#[cfg(test)]
mod tests {
    use serde_json::{json, to_value};

    use super::*;

    #[test]
    fn serialize_default_splom() {
        let trace = Splom::<f64>::default();
        let expected = json!({"type": "splom"}).to_string();

        assert_eq!(trace.to_json(), expected);
    }

    #[test]
    fn serialize_basic_splom_trace() {
        let trace = Splom::new()
            .name("splom")
            .dimensions(vec![
                SplomDimension::new().label("A").values(vec![1.0, 2.0, 3.0]),
                SplomDimension::new().label("B").values(vec![4.0, 5.0, 6.0]),
            ])
            .diagonal(SplomDiagonal::new().visible(false))
            .show_upper_half(false)
            .marker(Marker::new().size(4).opacity(0.6));

        let expected = json!({
            "type": "splom",
            "name": "splom",
            "dimensions": [
                {"label": "A", "values": [1.0, 2.0, 3.0]},
                {"label": "B", "values": [4.0, 5.0, 6.0]}
            ],
            "diagonal": {"visible": false},
            "showupperhalf": false,
            "marker": {"size": 4, "opacity": 0.6}
        });

        assert_eq!(to_value(trace).unwrap(), expected);
    }

    #[test]
    fn serialize_splom_dimension_axis() {
        let dim = SplomDimension::new()
            .label("A")
            .values(vec![1, 2, 3])
            .visible(true)
            .axis(SplomAxis::new().r#type(AxisType::Log).matches(true));

        let expected = json!({
            "label": "A",
            "values": [1, 2, 3],
            "visible": true,
            "axis": {"type": "log", "matches": true}
        });

        assert_eq!(to_value(dim).unwrap(), expected);
    }
}
