[package]
name = "multiple_plots_example"
version = "0.1.0"
edition = "2021"

[dependencies]
plotly = { path = "../../../plotly" }
plotly_utils = { path = "../../plotly_utils" }
build_html = "2.5.0"
ndarray = "0.16" 