[package]
name = "maps"
version = "0.1.0"
authors = ["Michael Freeborn <michaelfreeborn1@gmail.com>"]
edition = "2021"

[dependencies]
plotly = { path = "../../plotly" }
plotly_utils = { path = "../plotly_utils" }
csv = "1.3"
reqwest = { version = "0.11", features = ["blocking"] }

