name: Publish plotly-kaleido

on:
  workflow_dispatch:

jobs:
  create-crates-io-release:
    name: Deploy to crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo login ${{ env.CRATES_IO_TOKEN }}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - run: cargo publish --allow-dirty -p plotly_kaleido