name: Publish all

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-crates-io-release:
    name: Deploy to crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo login ${{ env.CRATES_IO_TOKEN }}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - name: Setup Chrome (for static_export)
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'
        install-chromedriver: true        
    - run: cargo publish --allow-dirty -p plotly_derive
    - run: sleep 10
    - run: cargo publish --allow-dirty -p plotly_kaleido
    - run: sleep 10
    - run: cargo publish --allow-dirty -p plotly
    # plotly_static is not part of the same ecosystem yet so it doesn't use the same TOKEN
    # - run: sleep 10
    # - run: cargo publish --allow-dirty -p plotly_static --features webdriver_download,chromedriver

  create-gh-release:
    name: Deploy to GH Releases
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1